#
# Fission Workflows chart configuration
#

# Bundle image
bundleImage: fission/fission-workflows-bundle

# Image of the Fission environment for Fission Workflows
envImage: fission/workflow-env

# Image of the Fission build environment for Fission Workflows
buildEnvImage: fission/workflow-build-env

tag: 0.1.3

pullPolicy: IfNotPresent

# Deploy optional Workflow api-server?
apiserver: true

# Fission configuration
fnenv:
  fission:
    controller: http://controller.fission
    executor: http://executor.fission

# Message queue config
nats:
  authToken: defaultFissionAuthToken
  cluster: fissionMQTrigger
  location: nats-streaming:4222
